// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZv9nzPCefowzySJ8u6kPsa-LkASk3L7s',
    appId: '1:80169610465:web:bff465d8a5d8beebc3dba0',
    messagingSenderId: '80169610465',
    projectId: 'trogo-61f6a',
    authDomain: 'trogo-61f6a.firebaseapp.com',
    storageBucket: 'trogo-61f6a.firebasestorage.app',
    measurementId: 'G-3N206S9KGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0iR0o1WW4YhWKx029xixZ5Tv2f8lAljo',
    appId: '1:80169610465:android:edae937b327bd54ac3dba0',
    messagingSenderId: '80169610465',
    projectId: 'trogo-61f6a',
    storageBucket: 'trogo-61f6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjNB4WpObSYFMRf0ve3gGv35oeN6305Aw',
    appId: '1:80169610465:ios:bd3ff76ddc9a668cc3dba0',
    messagingSenderId: '80169610465',
    projectId: 'trogo-61f6a',
    storageBucket: 'trogo-61f6a.firebasestorage.app',
    iosBundleId: 'com.trogo.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjNB4WpObSYFMRf0ve3gGv35oeN6305Aw',
    appId: '1:80169610465:ios:555bdb48587937b9c3dba0',
    messagingSenderId: '80169610465',
    projectId: 'trogo-61f6a',
    storageBucket: 'trogo-61f6a.firebasestorage.app',
    iosBundleId: 'com.example.trogoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZv9nzPCefowzySJ8u6kPsa-LkASk3L7s',
    appId: '1:80169610465:web:f13834ab480d88aac3dba0',
    messagingSenderId: '80169610465',
    projectId: 'trogo-61f6a',
    authDomain: 'trogo-61f6a.firebaseapp.com',
    storageBucket: 'trogo-61f6a.firebasestorage.app',
    measurementId: 'G-CYLMW9JM2D',
  );

}